name: 🐛 Bug Report
description: Use this form to report a reproducible bug or regression in PropMan.
title: "[BUG] "
labels: ["bug", "needs triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for helping us squash bugs! Please fill out the details below. Note: After submitting, you can add screenshots or video recordings by commenting on the ticket. Just look for the paperclip icon to upload your files."

  - type: checkboxes
    id: pre-check
    attributes:
      label: Preliminary checklist
      description: Please confirm the following item before you submit the issue.
      options:
        - label: "I have searched the existing issues and confirm this issue has not been reported before."
          required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: "A concise description of what you're experiencing."
      placeholder: "Describe the bug..."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A concise description of what you expected to happen."
      placeholder: "What did you expect to happen?"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "Provide detailed steps to reproduce the issue."
      placeholder: "1. Signed up with Google '...'\n2. Tapped on '....'\n3. Scroll down to '....'\n4. See error"
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: "Select the environment where the issue occurred."
      options:
        - "Android"
        - "iOS"
    validations:
      required: true

  - type: checkboxes
    id: final-check
    attributes:
      label: Final check
      description: Please confirm the following item before you submit the issue.
      options:
        - label: "I have carefully provided all necessary details and avoided using any placeholders or dummy content just to open the ticket."
          required: true
        - label: "I understand that submitting dummy or placeholder content will result in the automatic closure of the ticket."
          required: true
        - label: "I understand that to upload screenshots, I simply need to attach them by commenting on this issue after it has been opened."
          required: true


